baseURL: "https://zhihanz.github.io"
title: "zhihanz"
description: "Building at the intersection of GenAI, agentic workflows, and data infrastructure."
author: "zhihanz"
pagination: 10

social:
  github: "zhihanz"
  email: "zzh243402448@gmail.com"
  twitter: "zhihanz1205"
  linkedin: "zhihanzzz"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Posts"
      url: "/posts/"
      weight: 2
    - name: "Series"
      url: "/series/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - name: "About"
      url: "/about/"
      weight: 5

giscus:
  repo: "ZhiHanZ/zhihanz.github.io"
  repoId: "MDEwOlJlcG9zaXRvcnkzNDU2OTAwMDU="
  category: "Announcements"
  categoryId: "DIC_kwDOFJrPlc4C0z6O"
